image: registry.gitlab.com/gitlab-com/runbooks:2.1.0

stages:
  - test
  - deploy

test:
  script:
    - /prometheus/promtool check rules alerts/*.yml
    - /prometheus/promtool check rules recordings/*.yml
    - /prometheus/promtool check rules rules/*.yml

deploy_elast_watcher_updates:
  stage: deploy
  script:
    - elastic-watcher/update-alerts.sh
#  only:
#    - master
